package itc.fundraising.enums;

public enum ExpenseContract {

    PENYALURAN_DANA_ZAKAT,
    PENYALURAN_DANA_INFAK_SEDEKAH,
    PENYALURAN_DANA_SOSIAL_KEAGAMAAN_LAINNYA,
    BEBAN_TUNJANGAN_NON_TUNAI

}
